name: Docker Image CD

on:
  push:
    branches: [master]

env:
  REDIS_VERSION: latest
  REDIS_SENTINEL_VERSION: latest
  REDIS_EXPORTER_VERSION: latest

jobs:
  build_redis:
    environment: build
    strategy:
      matrix:
        version: [v6.2.17, v7.0.15, v7.2.7, latest2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push multi-arch latest image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            REDIS_VERSION=${{ matrix.version }}
          tags: docker.io/jmunschnab/redis:${{ matrix.version }}

  build_redis_sentinel:
    environment: build
    strategy:
      matrix:
        version: [v6.2.14, v7.0.15, v7.2.6, latest2]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push multi-arch latest image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.sentinel
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            REDIS_SENTINEL_VERSION=${{ matrix.version }}
          tags: docker.io/jmunschnab/redis-sentinel:${{ matrix.version }}

  build_redis_exporter:
    environment: build
    strategy:
      matrix:
        version: [v1.48.0]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push multi-arch latest image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.exporter
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: |
            REDIS_EXPORTER_VERSION=${{ matrix.version }}
          tags: docker.io/jmunschnab/redis-exporter:${{ matrix.version }}
